smtp_gmail:
  address: smtp.gmail.com
  domain: gmail.com
  port: 587
  authentication: :plain
  user_name: jilv1024@gmail.com
  password: jilv2048
  enable_starttls_auto: :true
  from: jilv1024@gmail.com
smtp:
  address: smtp.163.com
  domain: 163.com
  port: 25
  authentication: :login
  user_name: jilvtrip@163.com
  password: a123456
  from: jilvtrip@163.com
smtp_jilv:
  address: smtp.exmail.qq.com
  domain: jilvtrip.com
  port: 587
  authentication: :plain
  user_name: no-reply@jilvtrip.com
  password: jilv5963
  enable_starttls_auto: :true
  from: no-reply@jilvtrip.com
smtp_local:
  address: 127.0.0.1
  port: 25
  domain: jilvtrip.com
